name: Run Mark Games Script

on:
  schedule:
    - cron: '59 23 * * 4' # Runs at 11:59, only on Thursday
    - cron: '58 6 * * 5' # Runs at 11:59, only on Friday
    - cron: '30 16 * * 0' # Runs at 4:30, only on Sunday
    - cron: '20 19 * * 0' # Runs at 7:20, only on Sunday
    - cron: '50 19 * * 0' # Runs at 7:50, only on Sunday
    - cron: '59 23 * * 0' # Runs at 11:59, only on Sunday
    - cron: '59 23 * * 1' # Runs at 11:59, only on Monday
  workflow_dispatch:

jobs:
  mark-games:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: node mark-games.js
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          CURRENT_WEEK: ${{ secrets.CURRENT_WEEK }}
          CURRENT_YEAR: ${{ secrets.CURRENT_YEAR }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
